---
# Variables to set for all program traces
globals:
  # Socket to open
  socketPath: /tmp/greggd.sock
  # Format for verbose output
  verboseFormat: influx

# Hash of all programs to load
programs:
  - source: ./csrc/opensnoop.c
    # Events to bind program to
    events:
      - type: kprobe
        loadFunc: trace_entry
        attachTo: do_sys_open
      - type: kretprobe
        loadFunc: trace_return
        attachTo: do_sys_open
    # What should we read from
    outputs:
      - type: BPF_PERF_OUTPUT
        id: opensnoop
        format:
          - name: id
            type: u64
          - name: pid
            type: u32
            isTag: true
          - name: uid
            type: u32
            isTag: true
          - name: ret
            type: int32
          - name: comm
            type: char[16]
          - name: fname
            type: char[255]
            isTag: true
            filter:
              "or":
                - "have-prefix": "/proc"
                - "have-prefix": "/sys"
          - name: flag
            type: int32
      - type: BPF_HASH
        id: infotmp
        poll: 1s
        format:
          - name: id
            type: u64
          - name: comm
            type: char[16]
          - name: fname
            type: char[255]
            isTag: true
          - name: flags
            type: int32
