---
# Variables to set for all program traces
globals:
  # Socket to open
  socketPath: /run/greggd.sock
  # Format for verbose output
  verboseFormat: influx

# Hash of all programs to load
programs:
  - source: /usr/share/greggd/c/opensnoop.c
    # Events to bind program to
    events:
      - type: kprobe
        loadFunc: trace_entry
        attachTo: do_sys_open
      - type: kretprobe
        loadFunc: trace_return
        attachTo: do_sys_open
    # What should we read from
    outputs:
      - type: BPF_PERF_OUTPUT
        id: opensnoop
        format:
          - name: id
            type: u64
          - name: pid
            type: u32
            isTag: true
          - name: uid
            type: u32
            isTag: true
          - name: ret
            type: int32
          - name: comm
            type: char[16]
          - name: fname
            type: char[255]
            isTag: true
            filter:
              "or":
                - "have-prefix": "\"/proc"
                - "have-prefix": "\"/sys"
          - name: flag
            type: int32
            formatString: "%#o"
  - source: /usr/share/greggd/c/tcplife.c
    # Events to bind program to
    events:
      - type: kprobe
        loadFunc: kprobe__tcp_set_state
        attachTo: tcp_set_state
    # ipv6 is left as an exercise to the reader
    # What should we read from
    outputs:
      - type: BPF_PERF_OUTPUT
        id: ipv4_events
        format:
          - name: pid
            type: u32
            isTag: true
          - name: laddr
            type: u32
            isIP: true
          - name: raddr
            type: u32
            isIP: true
          - name: lport
            type: u16
            isTag: true
          - name: rport
            type: u16
            isTag: true
          - name: rx_b
            type: u64
          - name: tx_b
            type: u64
          - name: span_us
            type: u64
          - name: comm
            type: char[16]
            isTag: true
          - name: uid
            type: u32
            isTag: true
