---

# Socket to open
socketPath: /run/greggd.sock

# Hash of all programs to load
programs:
  - source: ./csrc/opensnoop.c
    # Events to bind program to
    events:
      - type: kprobe
        loadFunc: trace_entry
        attachTo: sys_open
      - type: kretprobe
        loadFunc: trace_return
        attachTo: sys_open
    # What should we read from
    outputs:
      - type: BPF_PERF_OUTPUT
        id: events
        format:
          - name: id
            type: u64
          - name: ts
            type: u64
          - name: uid
            type: u32
          - name: ret
            type: int32
          - name: comm
            type: char[16]
          - name: fname
            type: char[255]
          - name: flags
            type: int32
            #      - type: BPF_HASH
            #        id: hash
            #        poll: 1s
            #        format:
            #          - name: id
            #            type: u64
            #          - name: comm
            #            type: char[]
            #          - name: fname
            #            type: char[]
            #          - name: flags
            #            type: int
